# Test for linear Q8 quadrilateral.

In [6]:
import numpy as np
import sympy as sp


## Linear shape functions in [-1,1]

In [41]:
# Refrence element node coordinates
x0 = [-1,-1,-1]; x1 = [ 1,-1,-1]; x2 = [-1, 1,-1]; x3 = [ 1, 1,-1]
x4 = [-1,-1, 1]; x5 = [ 1,-1, 1]; x6 = [-1, 1, 1]; x7 = [ 1, 1, 1]

def L0(x):
    return (1-x)/2
def L1(x):
    return (1+x)/2

def dL0(x):
    return -1/2
def dL1(x):
    return 1/2

def N0(x,y,z):
    return L0(x)*L0(y)*L0(z)
def N1(x,y,z):
    return L1(x)*L0(y)*L0(z)
def N2(x,y,z):
    return L0(x)*L1(y)*L0(z)
def N3(x,y,z):
    return L1(x)*L1(y)*L0(z)
def N4(x,y,z):
    return L0(x)*L0(y)*L1(z)
def N5(x,y,z):
    return L1(x)*L0(y)*L1(z)
def N6(x,y,z):
    return L0(x)*L1(y)*L1(z)
def N7(x,y,z):
    return L1(x)*L1(y)*L1(z)

def dN0(x,y,z):
    return [dL0(x)*L0(y)*L0(z), L0(x)*dL0(y)*L0(z), L0(x)*L0(y)*dL0(z)]
def dN1(x,y,z):
    return [dL1(x)*L0(y)*L0(z), L1(x)*dL0(y)*L0(z), L1(x)*L0(y)*dL0(z)]
def dN2(x,y,z):
    return [dL0(x)*L1(y)*L0(z), L0(x)*dL1(y)*L0(z), L0(x)*L1(y)*dL0(z)]
def dN3(x,y,z):
    return [dL1(x)*L1(y)*L0(z), L1(x)*dL1(y)*L0(z), L1(x)*L1(y)*dL0(z)]
def dN4(x,y,z):
    return [dL0(x)*L0(y)*L1(z), L0(x)*dL0(y)*L1(z), L0(x)*L0(y)*dL1(z)]
def dN5(x,y,z):
    return [dL1(x)*L0(y)*L1(z), L1(x)*dL0(y)*L1(z), L1(x)*L0(y)*dL1(z)]
def dN6(x,y,z):
    return [dL0(x)*L1(y)*L1(z), L0(x)*dL1(y)*L1(z), L0(x)*L1(y)*dL1(z)]
def dN7(x,y,z):
    return [dL1(x)*L1(y)*L1(z), L1(x)*dL1(y)*L1(z), L1(x)*L1(y)*dL1(z)]


def dN(i, x,y,z) : 
    if i == 0:
        return dN0(x,y,z)
    elif i == 1:
        return dN1(x,y,z)
    elif i == 2:
        return dN2(x,y,z)
    elif i == 3:
        return dN3(x,y,z)
    elif i == 4:
        return dN4(x,y,z)
    elif i == 5:
        return dN5(x,y,z)
    elif i == 6:
        return dN6(x,y,z)
    elif i == 7:
        return dN7(x,y,z)


## Finite Element interpolation Matrices for 8 node hexahedral element (Lineal Elasticity)

In [25]:
# 3D Strain displacement matrix B
def B(x,y,z):
    return np.array([
         [dN0(x,y,z)[0],0,0, dN1(x,y,z)[0],0,0, dN2(x,y,z)[0],0,0, dN3(x,y,z)[0],0,0, dN4(x,y,z)[0],0,0, dN5(x,y,z)[0],0,0, dN6(x,y,z)[0],0,0, dN7(x,y,z)[0],0,0],
         [0,dN0(x,y,z)[1],0, 0,dN1(x,y,z)[1],0, 0,dN2(x,y,z)[1],0, 0,dN3(x,y,z)[1],0, 0,dN4(x,y,z)[1],0, 0,dN5(x,y,z)[1],0, 0,dN6(x,y,z)[1],0, 0,dN7(x,y,z)[1],0],
         [0,0,dN0(x,y,z)[2], 0,0,dN1(x,y,z)[2], 0,0,dN2(x,y,z)[2], 0,0,dN3(x,y,z)[2], 0,0,dN4(x,y,z)[2], 0,0,dN5(x,y,z)[2], 0,0,dN6(x,y,z)[2], 0,0,dN7(x,y,z)[2]],
         [0,dN0(x,y,z)[2],dN0(x,y,z)[1], 0,dN1(x,y,z)[2],dN1(x,y,z)[1], 0,dN2(x,y,z)[2],dN2(x,y,z)[1], 0,dN3(x,y,z)[2],dN3(x,y,z)[1], 0,dN4(x,y,z)[2],dN4(x,y,z)[1], 0,dN5(x,y,z)[2],dN5(x,y,z)[1], 0,dN6(x,y,z)[2],dN6(x,y,z)[1], 0,dN7(x,y,z)[2],dN7(x,y,z)[1]],
         [dN0(x,y,z)[2],0,dN0(x,y,z)[0], dN1(x,y,z)[2],0,dN1(x,y,z)[0], dN2(x,y,z)[2],0,dN2(x,y,z)[0], dN3(x,y,z)[2],0,dN3(x,y,z)[0], dN4(x,y,z)[2],0,dN4(x,y,z)[0], dN5(x,y,z)[2],0,dN5(x,y,z)[0], dN6(x,y,z)[2],0,dN6(x,y,z)[0], dN7(x,y,z)[2],0,dN7(x,y,z)[0]],
         [dN0(x,y,z)[1],dN0(x,y,z)[0],0, dN1(x,y,z)[1],dN1(x,y,z)[0],0, dN2(x,y,z)[1],dN2(x,y,z)[0],0, dN3(x,y,z)[1],dN3(x,y,z)[0],0, dN4(x,y,z)[1],dN4(x,y,z)[0],0, dN5(x,y,z)[1],dN5(x,y,z)[0],0, dN6(x,y,z)[1],dN6(x,y,z)[0],0, dN7(x,y,z)[1],dN7(x,y,z)[0],0] 
        ])
    
np.set_printoptions(linewidth=np.inf)
display(B( 0.57735,-0.57735,-0.57735))
#display(B(-0.57735, 0.57735,-0.57735))
#display(B(-0.57735,-0.57735,-0.57735))
#display(B( 0.57735, 0.57735,-0.57735))
#display(B(-0.57735,-0.57735, 0.57735))
#isplay(B( 0.57735,-0.57735, 0.57735))
#display(B(-0.57735, 0.57735, 0.57735))
#display(B( 0.57735, 0.57735, 0.57735))
 


array([[-0.31100413,  0.        ,  0.        ,  0.31100413,  0.        ,  0.        , -0.08333337,  0.        ,  0.        ,  0.08333337,  0.        ,  0.        , -0.08333337,  0.        ,  0.        ,  0.08333337,  0.        ,  0.        , -0.02232913,  0.        ,  0.        ,  0.02232913,  0.        ,  0.        ],
       [ 0.        , -0.08333337,  0.        ,  0.        , -0.31100413,  0.        ,  0.        ,  0.08333337,  0.        ,  0.        ,  0.31100413,  0.        ,  0.        , -0.02232913,  0.        ,  0.        , -0.08333337,  0.        ,  0.        ,  0.02232913,  0.        ,  0.        ,  0.08333337,  0.        ],
       [ 0.        ,  0.        , -0.08333337,  0.        ,  0.        , -0.31100413,  0.        ,  0.        , -0.02232913,  0.        ,  0.        , -0.08333337,  0.        ,  0.        ,  0.08333337,  0.        ,  0.        ,  0.31100413,  0.        ,  0.        ,  0.02232913,  0.        ,  0.        ,  0.08333337],
       [ 0.        , -0.08333337, -0.

## Jacobian

In [43]:
X0 = np.array([0.0, 4.0, 5.0])
X1 = np.array([0.0, 0.0, 5.0])
X2 = np.array([0.0, 4.0, 0.0])
X3 = np.array([0.0, 0.0, 0.0])
X4 = np.array([6.0, 4.0, 5.0])
X5 = np.array([6.0, 0.0, 5.0])
X6 = np.array([6.0, 4.0, 0.0])
X7 = np.array([6.0, 0.0, 0.0])

coord_array = np.array([X0,X1,X2,X3,X4,X5,X6,X7])

for i in range(8):
        display(coord_array[i])

def J(x,y,z):
    J = np.zeros((3,3))
    for k in range(8):
          for i in range(3):
              for j in range(3):
                  J[i,j] += coord_array[k][i]*dN(k,x,y,z)[j]

    return J

display(J(-0.57735, -0.57735,-0.57735))

def detJ(x,y,z):
    return np.linalg.det(J(x,y,z))

display(detJ(-0.57735, -0.57735,-0.57735))

array([0., 4., 5.])

array([0., 0., 5.])

array([0., 4., 0.])

array([0., 0., 0.])

array([6., 4., 5.])

array([6., 0., 5.])

array([6., 4., 0.])

array([6., 0., 0.])

array([[ 0.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [-2.00000000e+00,  0.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00, -2.50000000e+00,  0.00000000e+00]])

15.000000000000007

## Material Properties
Lineal Strain-Stress relation

In [28]:
E  = 200
nu = 0.3

G = E/(2*(1+nu))
C = np.array([
    [E,0,0,0,0,0],
    [0,E,0,0,0,0],
    [0,0,E,0,0,0],
    [0,0,0,G,0,0],
    [0,0,0,0,G,0],
    [0,0,0,0,0,G]
])

#C = E/(1-nu**2)*np.array([
#    [1,nu,nu,0,0,0],
#    [nu,1,nu,0,0,0],
#    [nu,nu,1,0,0,0],
#    [0,0,0,(1-nu)/2,0,0],
#    [0,0,0,0,(1-nu)/2,0],
#    [0,0,0,0,0,(1-nu)/2]
#])

display(C)


array([[200.        ,   0.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        , 200.        ,   0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        , 200.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  76.92307692,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,  76.92307692,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,   0.        ,  76.92307692]])

## $BtCB(x)$

In [61]:
def BtCB(x,y,z):
    return np.matmul(np.transpose(B(x,y,z)),np.matmul(C,B(x,y,z)))

def BtCBdetJ(x,y,z):
    return BtCB(x,y,z)*detJ(x,y,z)

#display(BtCB    (-0.57735,-0.57735,-0.57735))
display(BtCBdetJ(-0.57735,-0.57735,-0.57735))

array([[ 5.13378935e+02,  1.11604116e+02,  1.11604116e+02, -2.30362189e+02, -1.11604116e+02, -1.11604116e+02, -3.94879116e+00,  2.99042570e+01,  2.99042570e+01, -9.96424972e+01, -2.99042570e+01, -2.99042570e+01, -3.94879116e+00,  2.99042570e+01,  2.99042570e+01, -9.96424972e+01, -2.99042570e+01, -2.99042570e+01, -3.89751612e+01,  8.01282798e+00,  8.01282798e+00, -3.68590087e+01, -8.01282798e+00, -8.01282798e+00],
       [ 1.11604116e+02,  5.13378935e+02,  1.11604116e+02,  2.99042570e+01, -3.94879116e+00,  2.99042570e+01, -1.11604116e+02, -2.30362189e+02, -1.11604116e+02, -2.99042570e+01, -9.96424972e+01, -2.99042570e+01,  2.99042570e+01, -3.94879116e+00,  2.99042570e+01,  8.01282798e+00, -3.89751612e+01,  8.01282798e+00, -2.99042570e+01, -9.96424972e+01, -2.99042570e+01, -8.01282798e+00, -3.68590087e+01, -8.01282798e+00],
       [ 1.11604116e+02,  1.11604116e+02,  5.13378935e+02,  2.99042570e+01,  2.99042570e+01, -3.94879116e+00,  2.99042570e+01,  2.99042570e+01, -3.94879116e+00,  8.01

## Gauss Quadrature Testing

In [83]:
w0 = 1;
w1 = 1;
w2 = 1;

def gauss3D(f):
    xi_0 = [-1/np.sqrt(3), 1/np.sqrt(3)]
    xi_1 = [-1/np.sqrt(3), 1/np.sqrt(3)]
    xi_2 = [-1/np.sqrt(3), 1/np.sqrt(3)]
    
    A = 0
    for k in range(2):
        for j in range(2):
            for i in range(2):
                A += w0*w1*w2*f(xi_0[i],xi_1[j],xi_2[k])
                
    return A

 
K = gauss3D(BtCBdetJ)

display(K) 

# Eigenvalues of K
eigvals = np.linalg.eigvals(K)
display(eigvals)



array([[1179.48717949,  192.30769231,  192.30769231, -410.25641026, -192.30769231, -192.30769231,  205.12820513,  192.30769231,   96.15384615, -397.43589744, -192.30769231,  -96.15384615,  205.12820513,   96.15384615,  192.30769231, -397.43589744,  -96.15384615, -192.30769231,  -89.74358974,   96.15384615,   96.15384615, -294.87179487,  -96.15384615,  -96.15384615],
       [ 192.30769231, 1179.48717949,  192.30769231,  192.30769231,  205.12820513,   96.15384615, -192.30769231, -410.25641026, -192.30769231, -192.30769231, -397.43589744,  -96.15384615,   96.15384615,  205.12820513,  192.30769231,   96.15384615,  -89.74358974,   96.15384615,  -96.15384615, -397.43589744, -192.30769231,  -96.15384615, -294.87179487,  -96.15384615],
       [ 192.30769231,  192.30769231, 1179.48717949,  192.30769231,   96.15384615,  205.12820513,   96.15384615,  192.30769231,  205.12820513,   96.15384615,   96.15384615,  -89.74358974, -192.30769231, -192.30769231, -410.25641026, -192.30769231,  -96.15384615,

array([ 1.53846154e+03,  3.00000000e+03,  3.84615385e+02,  3.84615385e+02,  3.00000000e+03,  3.00000000e+03,  2.30769231e+03,  2.30769231e+03,  2.30769231e+03,  5.89743590e+02,  5.89743590e+02,  5.89743590e+02, -8.48509144e-13, -1.57148956e-13,  1.71003168e-13,  1.38461538e+03,  1.50459306e-13,  1.65376482e-14,  1.38461538e+03,  1.38461538e+03,  1.38461538e+03,  1.38461538e+03,  0.00000000e+00,  1.38461538e+03])

## Displacement Testing

The nodes at x0 = 0 will be constrained. That is: X0, X1, X2 and X3.


In [75]:
constrains = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1],
    [1,1,1],
    [0,0,0],
    [0,0,0],
    [0,0,0],
    [0,0,0]
]).flatten()

rest_index = np.where(constrains != 0)[0]
free_index = np.where(constrains == 0)[0]

display(rest_index)
display(free_index)

Knn = np.array([[K[i][j] for i in free_index] for j in free_index])
Kaa = np.array([[K[i][j] for i in rest_index] for j in rest_index])

display(Knn)
display(Kaa)

                      

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

array([[1179.48717949,  192.30769231, -192.30769231, -410.25641026, -192.30769231,  192.30769231,  205.12820513,  192.30769231,  -96.15384615, -397.43589744, -192.30769231,   96.15384615],
       [ 192.30769231, 1179.48717949, -192.30769231,  192.30769231,  205.12820513,  -96.15384615, -192.30769231, -410.25641026,  192.30769231, -192.30769231, -397.43589744,   96.15384615],
       [-192.30769231, -192.30769231, 1179.48717949, -192.30769231,  -96.15384615,  205.12820513,  -96.15384615, -192.30769231,  205.12820513,  -96.15384615,  -96.15384615,  -89.74358974],
       [-410.25641026,  192.30769231, -192.30769231, 1179.48717949, -192.30769231,  192.30769231, -397.43589744,  192.30769231,  -96.15384615,  205.12820513, -192.30769231,   96.15384615],
       [-192.30769231,  205.12820513,  -96.15384615, -192.30769231, 1179.48717949, -192.30769231,  192.30769231, -397.43589744,   96.15384615,  192.30769231, -410.25641026,  192.30769231],
       [ 192.30769231,  -96.15384615,  205.12820513,  1

array([[1179.48717949,  192.30769231,  192.30769231, -410.25641026, -192.30769231, -192.30769231,  205.12820513,  192.30769231,   96.15384615, -397.43589744, -192.30769231,  -96.15384615],
       [ 192.30769231, 1179.48717949,  192.30769231,  192.30769231,  205.12820513,   96.15384615, -192.30769231, -410.25641026, -192.30769231, -192.30769231, -397.43589744,  -96.15384615],
       [ 192.30769231,  192.30769231, 1179.48717949,  192.30769231,   96.15384615,  205.12820513,   96.15384615,  192.30769231,  205.12820513,   96.15384615,   96.15384615,  -89.74358974],
       [-410.25641026,  192.30769231,  192.30769231, 1179.48717949, -192.30769231, -192.30769231, -397.43589744,  192.30769231,   96.15384615,  205.12820513, -192.30769231,  -96.15384615],
       [-192.30769231,  205.12820513,   96.15384615, -192.30769231, 1179.48717949,  192.30769231,  192.30769231, -397.43589744,  -96.15384615,  192.30769231, -410.25641026, -192.30769231],
       [-192.30769231,   96.15384615,  205.12820513, -1

In [82]:
F = np.array([
        0.25, 0.0, 0.0,
        0.25, 0.0, 0.0,
        0.25, 0.0, 0.0,
        0.25, 0.0, 0.0])

display(F)

U = np.linalg.solve(Knn,F)

display(U.T)


array([0.25, 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.  ])

array([ 7.94444444e-04, -8.46108796e-20,  3.61111111e-04,  7.94444444e-04,  7.76942365e-20, -3.61111111e-04,  7.94444444e-04, -7.87645543e-20,  3.61111111e-04,  7.94444444e-04,  1.22191771e-19, -3.61111111e-04])